version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    ports: 
      - "27017:27017"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: bigbang-server-image
    container_name: bigbang-server-container
    restart: always
    ports:
      - "8000:8000"
    volumes: 
      - ./server/build:/index
    depends_on:
      - mongodb
    networks:
      - mern-network
    environment:
      - MONGO_URI= "mongodb://127.0.0.1:27017/bigbang?directConnection=true"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: bigbang-client-image
    container_name: bigbang-client-container
    command: npm run dev
    volumes:
      - ./client/:/usr/app
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - mern-network

networks:
    mern-network:
        driver: bridge

volumes:
    data: